export const CARD_TYPE_CONSTANTS = [
  'Action',
  'Treasure',
  'Event',
  'Attack',
  'Victory',
  'Reaction',
  'Duration',
  'Prize',
  'Curse',
  'Ruins',
  'Looter',
  'Knight',
  'Shelter',
  'Reserve',
  'Traveller',
  'Castle',
  'Gathering',
  'Landmark',
  'Fate',
  'Night',
  'Heirloom',
  'Doom',
  'Zombie',
  'Spirit',
  'Boon',
  'Hex',
  'State',
  'Artifact',
  'Project',
];

export const CARD_TAG_CLASSNAMES = {
  Action: 'action',
  Treasure: 'treasure',
  Event: 'event',
  Attack: 'attack',
  Victory: 'victory',
  Reaction: 'reaction',
  Duration: 'duration',
  Prize: 'prize',
  Curse: 'curse',
  Ruins: 'ruins',
  Looter: 'looter',
  Knight: 'knight',
  Shelter: 'shelter',
  Reserve: 'reserve',
  Traveller: 'traveler',
  Castle: 'castle',
  Gathering: 'gathering',
  Landmark: 'landmark',
  Fate: 'fate',
  Night: 'night',
  Heirloom: 'heirloom',
  Doom: 'doom',
  Zombie: 'zombie',
  Spirit: 'spirit',
  Boon: 'boon',
  Hex: 'hex',
  State: 'state',
  Artifact: 'artifact',
  Project: 'project',
};
