const numberShapes = [
  {
    number: 0,
    top: true,
    upperLeft: true,
    upperRight: true,
    middle: false,
    lowerLeft: true,
    lowerRight: true,
    bottom: true,
  },
  {
    number: 1,
    top: false,
    upperLeft: false,
    upperRight: true,
    middle: false,
    lowerLeft: false,
    lowerRight: true,
    bottom: false,
  },
  {
    number: 2,
    top: true,
    upperLeft: false,
    upperRight: true,
    middle: true,
    lowerLeft: true,
    lowerRight: false,
    bottom: true,
  },
  {
    number: 3,
    top: true,
    upperLeft: false,
    upperRight: true,
    middle: true,
    lowerLeft: false,
    lowerRight: true,
    bottom: true,
  },
  {
    number: 4,
    top: false,
    upperLeft: true,
    upperRight: true,
    middle: true,
    lowerLeft: false,
    lowerRight: true,
    bottom: false,
  },
  {
    number: 5,
    top: true,
    upperLeft: true,
    upperRight: false,
    middle: true,
    lowerLeft: false,
    lowerRight: true,
    bottom: true,
  },
  {
    number: 6,
    top: true,
    upperLeft: true,
    upperRight: false,
    middle: true,
    lowerLeft: true,
    lowerRight: true,
    bottom: true,
  },
  {
    number: 7,
    top: true,
    upperLeft: false,
    upperRight: true,
    middle: false,
    lowerLeft: false,
    lowerRight: true,
    bottom: false,
  },
  {
    number: 8,
    top: true,
    upperLeft: true,
    upperRight: true,
    middle: true,
    lowerLeft: true,
    lowerRight: true,
    bottom: true,
  },
  {
    number: 9,
    top: true,
    upperLeft: true,
    upperRight: true,
    middle: true,
    lowerLeft: false,
    lowerRight: true,
    bottom: false,
  },
];

export default numberShapes;
